version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "1521:1521"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/FREE as sysdba", "@healthcheck.sql" ]
      interval: 30s
      timeout: 10s
      retries: 5