openapi: "3.0.0"
info:
  title: Link Reduction API
  version: 2.0.0
paths:
  /link:
    post:
      summary: Create a new link
      tags:
        - LinkReduction
      operationId: createLink
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Link"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Link"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
components:
  schemas:
    Link:
      type: object
      properties:
        url:
          type: string
          format: uri
      required:
        - url
    Message:
      type: object
      properties:
        message:
          type: string
      required:
        - message