openapi: "3.0.0"
info:
  title: Link Reduction API
  version: 1.0.0
paths:
  /link:
    post:
      summary: Create a new link
      tags:
        - LinkReduction
      operationId: createLink
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LinkDTO"
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LinkDTO"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
components:
  schemas:
    LinkDTO:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    Message:
      type: object
      required:
        - message
      properties:
        message:
          type: string